import React from "react";

export function FooterDisclaimer() {
  return (
    <div className="mt-8 border-t border-white/10 pt-6 text-xs leading-relaxed text-white/70">
      <div className="font-semibold tracking-wide text-white/80">
        OPINION ONLY - NOT FINANCIAL ADVICE
      </div>
      <div className="mt-2">
        VerdictSwarm provides automated risk assessments based on public on-chain data. All
        "Verdicts" and "Risk Ratings" are opinions generated by AI models, not statements of
        fact. A "Flagged" rating does not accuse anyone of crimes. A "Low Risk" rating does not
        guarantee safety. Conduct your own research. We accept no liability for losses.
      </div>
    </div>
  );
}

export function PerVerdictDisclaimer() {
  return (
    <div className="rounded-md border border-amber-500/30 bg-amber-500/10 p-3 text-xs leading-relaxed text-amber-100">
      <div className="font-semibold tracking-wide">
        AUTOMATED RISK ASSESSMENT - OPINION ONLY
      </div>
      <div className="mt-2">
        This report is AI-generated based on on-chain heuristics. The risk level represents our
        model's opinion based on detected patterns. This is not an accusation of wrongdoing.
        <div className="mt-2">Verify all data on a block explorer.</div>
      </div>
    </div>
  );
}
